### ISSUE TITLE
Installation steps?

### ISSUE THREAD

**Issue by CleoQc** [PacktPublishing/React-and-React-Native-4th-Edition-#1]
Hello,
My React knowledge is at 0, and my Javascript isn't that  much better (I'm Python first). I am looking for the installation steps (not git clone, but how to run each example) and I can't find those steps in the book.
When I google, I find that I am expected to run 
` npm install` 
followed by `npm start` 
but that fails with 
```
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
```

I have Node.js v18.2.0 installed.  Am I missing some steps ?

**Comment by nithikpackt** [comment]
Hello @CleoQc ,seems like you have managed to find solution for the issue yourself. I am closing the issue for now
